-- ==============================================================================
-- VISITOR MANAGEMENT SYSTEM (VMS PRO) - FULL SUPABASE DATABASE SCHEMA
-- ==============================================================================
-- Run this complete script in your Supabase SQL Editor:
-- Supabase Dashboard -> SQL Editor -> "+ New query" -> Paste and click "Run"
-- ==============================================================================

-- 1. CLEANUP (Safe re-run if needed)
DROP TABLE IF EXISTS public.visitors CASCADE;
DROP TABLE IF EXISTS public.preregistered CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.hosts CASCADE;

-- ==============================================================================
-- 2. CREATE TABLES
-- ==============================================================================

-- 2.1 USERS TABLE (Authentication for Admin & Security Staff)
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'security', -- 'admin', 'security', 'kiosk'
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2.2 VISITORS TABLE (All registered & active visitors)
CREATE TABLE public.visitors (
    id TEXT PRIMARY KEY,                       -- e.g. 'VIS-20260930-0001'
    name TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    "hostName" TEXT,
    purpose TEXT,
    "photoData" TEXT,                         -- Base64 encoded visitor snapshot
    status TEXT NOT NULL DEFAULT 'registered', -- 'registered', 'checked-in', 'checked-out'
    "checkInTime" TIMESTAMPTZ,
    "checkOutTime" TIMESTAMPTZ,
    auth_pin TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2.3 PREREGISTERED TABLE (Expected visitors)
CREATE TABLE public.preregistered (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT,
    "hostName" TEXT NOT NULL,
    "expectedDate" TEXT NOT NULL,             -- Date string (YYYY-MM-DD)
    purpose TEXT,
    status TEXT NOT NULL DEFAULT 'expected',  -- 'expected', 'arrived'
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2.4 HOSTS TABLE (Telegram bot self-registration for private DM alerts)
CREATE TABLE public.hosts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    chat_id TEXT NOT NULL,
    telegram_username TEXT,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- 3. INDEXES FOR FAST SEARCH & FILTERING
-- ==============================================================================
CREATE INDEX idx_visitors_status ON public.visitors(status);
CREATE INDEX idx_visitors_checkInTime ON public.visitors("checkInTime" DESC);
CREATE INDEX idx_visitors_created_at ON public.visitors(created_at DESC);
CREATE INDEX idx_visitors_name ON public.visitors(name);
CREATE INDEX idx_preregistered_status ON public.preregistered(status);
CREATE INDEX idx_users_username ON public.users(username);
CREATE INDEX idx_hosts_name ON public.hosts(name);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preregistered ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hosts ENABLE ROW LEVEL SECURITY;

-- Allow public access via Supabase anon / authenticated clients
CREATE POLICY "Allow public all access on users" 
    ON public.users FOR ALL 
    TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow public all access on visitors" 
    ON public.visitors FOR ALL 
    TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow public all access on preregistered" 
    ON public.preregistered FOR ALL 
    TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow public all access on hosts" 
    ON public.hosts FOR ALL 
    TO anon, authenticated 
    USING (true) 
    WITH CHECK (true);

-- Grant schema permissions to standard Supabase roles
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.visitors TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.preregistered TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.hosts TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ==============================================================================
-- 5. REALTIME REPLICATION (For instant Kiosk QR & Dashboard live sync)
-- ==============================================================================
ALTER TABLE public.visitors REPLICA IDENTITY FULL;
ALTER TABLE public.preregistered REPLICA IDENTITY FULL;

-- Add tables to Supabase realtime publication
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'visitors'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.visitors;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'preregistered'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.preregistered;
    END IF;
END $$;

-- ==============================================================================
-- 6. DEFAULT SEED DATA
-- ==============================================================================
INSERT INTO public.users (username, password, role)
VALUES 
    ('admin', 'admin123', 'admin'),
    ('security', 'sec123', 'security')
ON CONFLICT (username) DO NOTHING;
